version: "3"

tasks:
  dev:
    desc: รันทั้งหน้าบ้านและหลังบ้าน
    deps: [web-dev, api-dev]

  web-dev:
    cmds:
      - cd apps/web && npm run dev

  api-dev:
    desc: run only Go Backend (Air for Live Reload)
    cmds:
      - cd apps/server && air

  db-up:
    desc: run supabase local
    cmds:
      - supabase start
