version: '3'

tasks:
  dev:
    desc: "Start everything for Badminton Project"
    deps: [web, api]

  web:
    desc: "Start Next.js Frontend"
    cmds:
      - npx turbo dev

  api:
    desc: "Start Golang Backend with Air"
    dir: apps/server
    cmds:
      - air

  db-start:
    desc: "Start Local Supabase"
    cmds:
      - supabase start

  db-stop:
    desc: "Stop Local Supabase"
    cmds:
      - supabase stop

  db-reset:
    desc: "Reset DB and Seed data"
    cmds:
      - supabase db reset